#cloud-config
preserve_hostname: true

{{ growpart_str }}

write_files:
{{ eth1_str }}

{{ firewall_files }}

{{ ssh_files }}

{{ init_files }}

packages: [{{ packages_str }}]

runcmd:
{{ post_create_commands_str }}
