name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.1'

      - name: "Install dependencies"
        run: |
          brew install squashfs openssl@1.1

      - name: Build for macOS
        run: |
          wget https://github.com/pmq20/ruby-packer/releases/download/darwin-x64/rubyc
          chmod +x rubyc
          ./rubyc -r ./ -o ./hetzner-k3s-macos exe/hetzner-k3s --openssl-dir=/usr/local/etc/openssl@1.1/

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          artifacts: "hetzner-k3s-macos"
          token: ${{ secrets.GITHUB_TOKEN }}
